# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favotie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favotie',
            new_name='is_favorite',
        ),
    ]
